### ISSUE TITLE
Error in p4 submit with ST3

### ISSUE THREAD

**Issue by asomorjai** [ericmartel/Sublime-Text-2-Perforce-Plugin#23]
Hi Eric,

While trying to submit a file, I got the following error message:

Exception in thread Thread-4:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "Perforce in /Users/somorjai/Library/Application Support/Sublime Text 3/Installed Packages/Perforce.sublime-package", line 921, in run
  File "Perforce in /Users/somorjai/Library/Application Support/Sublime Text 3/Installed Packages/Perforce.sublime-package", line 894, in MakeChangelistsList
  File "Perforce in /Users/somorjai/Library/Application Support/Sublime Text 3/Installed Packages/Perforce.sublime-package", line 164, in GetPendingChangelists
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 3384: invalid continuation byte

I'm using the OSX ST3 build 3052.

Any ideas?

Thanks, Akos

**Comment by ericmartel** [comment]
Hi Akos,

Please use the Sublime Text 3 version here: https://github.com/ericmartel/Sublime-Text-3-Perforce-Plugin

Last night I wrote a backward compatibility for ST2 for another of my plugin, I'll add it to the Perforce Plugin over the week end!

Thanks

Eric
